version: 2

models:
  - name: fct_orders
    description: "Tabela fato de pedidos com dados de cliente e pagamento."

    columns:
      - name: order_id
        description: "Identificador único do pedido."
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "Identificador do cliente associado ao pedido."
        tests:
          - not_null

      - name: payment_id
        description: "Identificador do pagamento associado ao pedido."
        tests:
          - unique
          - not_null

      - name: amount
        description: "Valor pago no pedido."
        tests:
          - not_null